# Generated by Django 5.1.5 on 2025-03-20 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TourDescription',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('countries', models.CharField(max_length=255)),
                ('cities', models.CharField(blank=True, max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('departure_from', models.CharField(max_length=100)),
                ('departure_by', models.CharField(max_length=100)),
                ('return_from', models.CharField(max_length=100)),
                ('food', models.CharField(max_length=100)),
                ('adults', models.IntegerField(default=0)),
                ('children', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('promotion', models.BooleanField(default=False)),
                ('price_promotion', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('hot_deal', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TourDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program', models.TextField()),
                ('services', models.JSONField(default=list)),
                ('noservices', models.JSONField(default=list)),
                ('festivals', models.BooleanField(default=False)),
                ('beach_tour', models.BooleanField(default=False)),
                ('winter_tour', models.BooleanField(default=False)),
                ('extreme_tour', models.BooleanField(default=False)),
                ('natural_tour', models.BooleanField(default=False)),
                ('gastronomic_tour', models.BooleanField(default=False)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='tours.tourdescription')),
            ],
        ),
        migrations.CreateModel(
            name='TourPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('tour_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='tours.tourdetail')),
            ],
        ),
    ]
