# Generated by Django 5.1.5 on 2025-04-02 10:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tours", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tourdescription",
            name="available_seats",
            field=models.PositiveIntegerField(default=10),
        ),
    ]
