# Generated by Django 5.1.5 on 2025-04-08 08:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tours", "0005_agencyreview"),
    ]

    operations = [
        migrations.AddField(
            model_name="agencyreview",
            name="cons",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="agencyreview",
            name="pros",
            field=models.TextField(blank=True),
        ),
    ]
