# Generated by Django 5.1.5 on 2025-03-26 15:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_cabinet", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartitem",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 4, 25, 15, 26, 47, 576915, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
