# Generated by Django 5.1.5 on 2025-04-02 11:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_cabinet", "0005_alter_cartitem_expires_at_order_booking"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartitem",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 5, 2, 11, 12, 18, 939139, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
