# Generated by Django 5.1.5 on 2025-04-02 17:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_cabinet", "0006_alter_cartitem_expires_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartitem",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 5, 2, 17, 28, 47, 842095, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
