# Generated by Django 5.1.5 on 2025-04-02 17:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_cabinet", "0008_alter_booking_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartitem",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 5, 2, 17, 36, 53, 162787, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
