# Generated by Django 5.1.5 on 2025-04-04 16:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_cabinet', '0010_alter_cartitem_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 4, 16, 7, 13, 916741, tzinfo=datetime.timezone.utc)),
        ),
    ]
