# Generated by Django 5.1.5 on 2025-04-04 16:48

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_tourdescription_available_seats'),
        ('user_cabinet', '0011_alter_cartitem_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 4, 16, 48, 34, 632639, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='tours.tourdescription'),
        ),
    ]
