# Generated by Django 5.1.5 on 2025-04-07 10:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_cabinet", "0012_alter_cartitem_expires_at_alter_order_tour"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartitem",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 5, 7, 10, 41, 51, 959040, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
