# Generated by Django 5.1.5 on 2025-04-08 08:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_cabinet", "0025_alter_cartitem_expires_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartitem",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 5, 8, 8, 48, 13, 611252, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
