# Generated by Django 5.1.5 on 2025-04-09 08:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_cabinet', '0029_alter_cartitem_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 9, 8, 53, 44, 968316, tzinfo=datetime.timezone.utc)),
        ),
    ]
