# Generated by Django 5.1.5 on 2025-04-10 12:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_cabinet', '0032_alter_cartitem_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 10, 12, 23, 16, 390907, tzinfo=datetime.timezone.utc)),
        ),
    ]
