# Generated by Django 5.1.5 on 2025-04-14 12:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_cabinet", "0034_order_payment_id_alter_cartitem_expires_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartitem",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 5, 14, 12, 24, 35, 99757, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
