# Generated by Django 5.1.5 on 2025-04-14 12:24

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_cabinet", "0035_alter_cartitem_expires_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookingpayment",
            name="liqpay_order_id",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="bookingpayment",
            name="liqpay_payment_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="bookingpayment",
            name="liqpay_status",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="bookingpayment",
            name="booking",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payment",
                to="user_cabinet.booking",
            ),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 5, 14, 12, 24, 52, 582684, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
