# Generated by Django 5.1.5 on 2025-04-14 12:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_cabinet", "0036_bookingpayment_liqpay_order_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartitem",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 5, 14, 12, 32, 28, 289322, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
