# Generated by Django 5.1.5 on 2025-06-17 12:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_cabinet', '0038_alter_cartitem_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 17, 12, 17, 46, 237945, tzinfo=datetime.timezone.utc)),
        ),
    ]
